AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: build/data-loader
      Runtime: go1.x
      Timeout: 20
      Environment:
        Variables:
          ENVIRONMENT_NAME: dev
          DATA_BUCKET: data-loader-dev-us-west-2-data
          SCHEMA_BUCKET: data-loader-dev-us-west-2-schemas